// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidproduction;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidproduction = FirebaseOptions(
    apiKey: 'AIzaSyCoX9GOCvXwa-690dH5pCmjB1ePj8PqsG8',
    appId: '1:987466458725:android:8ea7c5ec9a36a37f18088c',
    messagingSenderId: '987466458725',
    projectId: 'pakistan-brands',
    storageBucket: 'pakistan-brands.appspot.com',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCoX9GOCvXwa-690dH5pCmjB1ePj8PqsG8",
      authDomain: "pakistan-brands.firebaseapp.com",
      projectId: "pakistan-brands",
      storageBucket: "pakistan-brands.appspot.com",
      messagingSenderId: "954285103347",
      appId: "1:954285103347:web:932927a23eeb1726017f86");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatlhMmtJIu6ihwQd8PAx5OhgEf5QvZBw',
    appId: '1:954285103347:android:30d83c76c96fe117017f86',
    messagingSenderId: '954285103347',
    projectId: 'leo-dev-store',
    storageBucket: 'leo-dev-store.firebasestorage.app',
  );
}
